server:
  port: 8081
spring:
  application:
    name: certifcate-service
  datasource:
    url: jdbc:mysql://localhost:3306/udemy_spring_training?serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

