server:
  port: 8080
spring:
  application:
    name: welcome-service
  datasource:
    url: jdbc:mysql://localhost:3306/udemy_spring_training?serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

